# services:
#   postgres:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: 0GWGwCMtouJ8G6v
#       POSTGRES_PASSWORD: rRxYyjxDv30H84F
#       POSTGRES_DB: kataoffical
#     volumes:
#         - postgres:/data   
#     ports:
#       - "5432:5432"
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: katachanneloffical@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: rRxYyjxDv30H84F
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgres 
#   datalake_storage:
#       image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
#       container_name: datalake_minio
#       command: server /data --console-address ":9090"
#       ports:
#         - "9000:9000"
#         - "9090:9090"
#       environment:
#         MINIO_ROOT_USER: 0GWGwCMtouJ8G6v
#         MINIO_ROOT_PASSWORD: rRxYyjxDv30H84F
#       volumes:
#         - minio_data:/data
#       healthcheck:
#         test: ["CMD", "mc", "ready", "local"]
#         interval: 5s
#         timeout: 5s
#         retries: 5
#         start_period: 5s
#   redis:
#     image: redis:7-alpine
#     container_name: redis_cache
#     command: redis-server --save 60 1 --loglevel warning
#     volumes:
#       - redis_data:/data
#     ports:
#       - "6379:6379"
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   # --- Backend Services ---
#   api:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#     container_name: api
#     environment:
#       NODE_ENV: development
#       PORT: 3200
#     ports:
#       - "3200:3200"
#     restart: unless-stopped

#   site:
#     build:
#       context: ./site
#       dockerfile: Dockerfile
#     container_name: site
#     ports:
#       - "4200:4200"
#     restart: unless-stopped
# volumes:
#   minio_data:
#   redis_data:
#   postgres:
#     driver: local